### PR TITLE
Date Fix

### PR DESCRIPTION
**Pull request by ben182**
Issue #6 fixed

### CODE REVIEW

**Comment by donatj** [comment]
Can you explain the issue this fixes with perhaps some example code?

**Comment by ben182** [comment]
As in Issue #6 explained, I fixed the today bug. When you initalize the calendar to the current month it doesnt hightlight the today item correctly. It highlights the very first of the month each time. This was caused by not correctly referencing to the current date in the each day loop.

**Comment by donatj** [comment]
Oh, I see.

Thank you very much for the explanation as I didn't understand what was the actual complaint in #6. 

So you're calling new `new \donatj\SimpleCalendar("April 2017")` where "April 2017" is the current month and year without specifying the day of the month. Hmm…

The ability to specify the day is technically intended as a "feature", but it's kind of ham handedly implemented. 

I had not considered that someone wouldn't just omit the parameter for the current month.  Ala `new \donatj\SimpleCalendar()` which will highlight the current day correctly.

because if you specify for instance April 22 2017 it picks April 22nd.  
screen shot 2017-04-03 at 12 18 24 pm

Current month and highlighted day should be seperate parameters not jammed together. I will accept your PR, but I'm afraid I'm not going to tag a release right now as it's a breaking change. 

This evening when I get home from work I will start deving current date as an optional separate parameter so you can still control the "current date".

**Comment by ben182** [comment]
I thought that the Class can be called like this 
`new \donatj\SimpleCalendar("April 2017")`
because even your Readme explained it so: https://github.com/donatj/SimpleCalendar#sample-usage

**Comment by donatj** [comment]
@ben182 It can, yes. 

The issue is when the month and year are the _current_ month and year, it also uses the day of that date to select which day to display. It's a bad behaviour, but also a "feature". 

As noted, I should break that into a separate parameter.  I just have not had a lot of time of late, but that's coming soon.

**Comment by donatj** [comment]
This was merged into the 1.x development branch. The final fix however is a little different, I've added a seperate "Today" date value from the current calendar value, which before were kinda of the same value.

**Comment by donatj** [comment]
@ben182 It's sad on my part but this finally made it into a release - see: https://github.com/donatj/SimpleCalendar/releases/tag/v0.7.0

**Pull request merged**
