### PR TITLE
Use custom classes in the calendar

### PR DESCRIPTION
**Pull request by keesiemeijer**
This PR adds custom control over the classes used in the calendar. It allows you to have calendars styled differently from the base style (e.g. `table.SimpleCalendar.small`). It can also fix conflicts with styles from other packages using the same class selectors as used in the calendar (e.g. `.today`, `.event`).

Example using custom classes.

```php
$calendar = new donatj\SimpleCalendar();
// add a `small` class to the calendar
$calendar->setCalendarClasses( array( 'calendar' => 'SimpleCalendar small' ) );
$calendar->addDailyHtml( 'Sample Event', 'today', 'tomorrow' );
$calendar->show( true );
```

This pr also adds a `div.events` container for the events. This allows you to add a scroll bar to a `td` tag.
https://stackoverflow.com/a/14058571

### CODE REVIEW

**Comment by donatj** [comment]
Thank you for your PR! I am currently in process of a fairly major rewrite as this code is all in all kinda creeky. However it will include the ability to change class names, as well as some other problems handling "shown date" vs "current date".

I will take your wrapping of the day's events into consideration though as that is a nice feature I had not considered.

I will leave this open for the time being as a reminder that I need to get that out the door. Thank you.

**Comment by keesiemeijer** [comment]
I'm looking forward to the changes

**Comment by hopeseekr** [comment]
:100:  THANK YOU FOR THE PR!! 

I have successfully used this in my own app... If I remember, I'll post a link to the website here once it's launched!

**Comment by donatj** [comment]
This was merged into the 1.x branch at #12

**Comment by donatj** [comment]
@keesiemeijer / @hopeseekr - Well it's dumb but this finally made it into a release - see: https://github.com/donatj/SimpleCalendar/releases/tag/v0.7.0

**Pull request merged**
