### PR TITLE
Turn private properties/methods as protected

### PR DESCRIPTION
**Pull request by gwarnants**
To make it easier to extend the class without having to override everything

### CODE REVIEW

**Comment by donatj** [comment]
A protected member is considered part of your libraries API, which by propper semantic versioning means I can't change them without a major version increment. I can't change any of the internals without major increments.

It's generally accepted as best practice to [make each class or member as inaccessible as possible](https://medium.com/@pranitsawant01/item-13-minimise-accessibility-of-classes-and-members-1b89433aaae1#:~:text=thumb%20is%20simple%3A-,make%20each%20class%20or,possible,-.%20In%20other%20words).

By and large these are the inner workings of the library and are not intended as unchangable part of the public API.

If you've got a argument for why an individual method should be protected, I'm open, but I'm not interested in making just making everything protected.

**Comment by gwarnants** [comment]
Hello, I completely agree with these best practices, if we keep in mind that developers will probably need to extends your class and to provide a sufficient public API or let them access to crucial internal methods. Making everything private completely closes inheritance benefits... and what's the point of OOP if we can't extend classes ?
Dumb example : I want to change how the HTML in generated because I added a custom feature :
- I have to override the whole render() method. But I can't because it requires $now and $today properties which are private too
- There are no public method() getToday() or getNow() so i have no other choice to change these properties to protected. I'm thus breaking all the benefits of using a Composer dependency...
- But it's not yet ok. The render method also requires weekdays() which is private. So i override it too in my child class
- But weekdays() requires $weekDayNames --> change this property to protected
- But it's not enough. The render method also requires rotate()
- Then, again, same problem with $offset and $classes...
- So maybe it will be faster to look for an other calendar base class...

Imo turning private members/methods to protected doesn't break anything in your public interface so it doesn't need a major version bump (the reverse is obviously not true)

**Comment by donatj** [comment]
> Imo turning private members/methods to protected doesn't break anything in your public interface so it doesn't need a major version bump (the reverse is obviously not true)

No, adding to the API doesn't require a bump, but what it does is prevents me from doing any work on said internals down the line without a major version bump.

> So maybe it will be faster to look for an other calendar base class...

Yeah, maybe. This thing is 12 years old and pretty creaky. While it gets basic maintenance, it could really use a ground up rewrite.

Beyond all of that, I'd be curious to know what kind of changes you want to actually make to the HTML?  I feel like the output HTML is nice and semantic and pretty generally flexible and styleable. I'm curious what it's lacking.

**Comment by gwarnants** [comment]
For example I added new events types (birthdays, public holidays, weekends, ...) and needed class(es) on cells
I also needed to customize the table header to show current month name and controls for next/previous month
Also show day number in leading/trailing cells
A bullet to show the number of events on a day
And so on...

Your class might be a good base class to create more sophisticated calendars

**Pull request closed without merging**
